# Generated by Django 5.0.4 on 2024-04-15 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iserv', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExistingAccounts',
            new_name='ExistingAccount',
        ),
        migrations.RenameModel(
            old_name='IservGroups',
            new_name='IservGroup',
        ),
    ]
