# Generated by Django 5.0.4 on 2024-04-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iserv', '0002_rename_existingaccounts_existingaccount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='existingaccount',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='existingaccount',
            name='groups',
            field=models.ManyToManyField(blank=True, null=True, to='iserv.iservgroup'),
        ),
        migrations.AlterField(
            model_name='existingaccount',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='existingaccount',
            name='school_class',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='existingaccount',
            name='uid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
