# Generated by Django 5.0.4 on 2024-04-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iserv', '0003_alter_existingaccount_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='existingaccount',
            old_name='school_class',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='existingaccount',
            old_name='uid',
            new_name='class_information',
        ),
        migrations.AddField(
            model_name='existingaccount',
            name='created_at',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='existingaccount',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='existingaccount',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='existingaccount',
            name='import_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='existingaccount',
            name='internal_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='existingaccount',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='existingaccount',
            name='user_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
