# Generated by Django 5.0.4 on 2024-04-17 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iserv', '0004_rename_school_class_existingaccount_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='existingaccount',
            name='groups',
            field=models.ManyToManyField(blank=True, to='iserv.iservgroup'),
        ),
    ]
