# Generated by Django 5.0.4 on 2024-04-17 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divis', '0002_student_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='class_name',
            new_name='name',
        ),
    ]
