# Generated by Django 5.0.4 on 2024-04-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divis', '0003_rename_class_name_class_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='birth_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
