# Generated by Django 5.0.4 on 2024-04-17 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divis', '0004_alter_student_birth_date_alter_teacher_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='divis.teacher'),
        ),
    ]
