# Generated by Django 5.0.4 on 2024-04-17 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divis', '0005_alter_class_teacher'),
        ('iserv', '0005_alter_existingaccount_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='iserv_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iserv.existingaccount'),
        ),
    ]
