# Generated by Django 5.0.4 on 2024-04-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divis', '0006_student_iserv_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='classes', to='divis.student'),
        ),
    ]
