# Generated by Django 5.0.4 on 2024-05-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divis', '0007_alter_class_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='iserv_group_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
