# Generated by Django 5.0.4 on 2024-05-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divis', '0008_class_iserv_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='teacher_error_message',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
