# Generated by Django 5.0.4 on 2024-05-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divis', '0010_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='clear_existing_data',
            field=models.BooleanField(default=False),
        ),
    ]
