# Generated by Django 5.0.4 on 2024-06-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divis', '0012_student_eduport_mail_alter_student_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='teacher',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
