# Generated by Django 5.0.4 on 2024-06-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divis', '0013_alter_class_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='iserv_account',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
