# Generated by Django 5.0.4 on 2024-06-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divis', '0014_alter_student_iserv_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='father',
            name='child',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mother',
            name='child',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
