# Generated by Django 5.0.4 on 2024-07-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divis', '0015_alter_father_child_alter_mother_child'),
    ]

    operations = [
        migrations.AlterField(
            model_name='father',
            name='child',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mother',
            name='child',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='iserv_account',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
