# Generated by Django 5.0.4 on 2024-07-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divis', '0016_alter_father_child_alter_mother_child_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='father',
            name='child',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mother',
            name='child',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
