# Generated by Django 5.0.4 on 2024-09-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divis', '0019_teacher_iserv_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='iserv_account',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='iserv_account',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
